pip-requirements.txt: Restrict antlr4-python3-runtime to 4.9
The ATN is serialized in different formats between antlr4-python3-runtime
4.9 and 4.10, meaning the latter can't deserialize data from the
former. See https://github.com/antlr/antlr4/issues/4568.

Until the file is updated and antlr-python3-runtime 4.10 or newer
is required, restrict us to using version 4.9.

This fixes the following error seen when using Python 3.13.3 and
antlr4-python3-runtime 4.13.2:

Run ECC tool for the commit in SecurityPkg/DeviceSecurity/SpdmLib/Include/hal
...
   self.checkVersion()
   ~~~~~~~~~~~~~~~~~^^
File ".../venv/lib/python3.13/site-packages/antlr4/atn/ATNDeserializer.py",
                                                  line 50, in checkVersion
raise Exception("Could not deserialize ATN with version {} (expected {}).".
                                  format(ord(version), SERIALIZED_VERSION))
Exception: Could not deserialize ATN with version 3 (expected 4).

Signed-off-by: Rebecca Cran <rebecca@bsdio.com>